import { Course } from "@schema/course";
import { writeSQLFile } from "@pipeline/io";

// ---------------------------------------------------------------------------
// SQL helpers
// ---------------------------------------------------------------------------

/** Escape a value for use in a SQL literal (single-quote escaping). */
function esc(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function bool(value: boolean): string {
  return value ? "TRUE" : "FALSE";
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export async function generateCourseSQLScript(path: string, courses: Course[]): Promise<void> {
  const lines: string[] = [
    "-- Auto-generated by pipeline/dataTransformer/generateCourseSQLScript.ts",
    "-- Idempotent: safe to run multiple times (ON CONFLICT DO NOTHING / DO UPDATE)",
    "",
  ];

  // -------------------------------------------------------------------------
  // 1) Collect unique lookup table entries
  // -------------------------------------------------------------------------

  const groups = new Map<string, { label: string; key: string }>();
  const subjects = new Map<string, { label: string; key: string }>();
  const variants = new Map<string, { label: string; short: string }>();
  const topicsMap = new Map<string, { label: string; hrefSlug: string }>();
  const chaptersMap = new Map<string, { label: string; hrefSlug: string }>();
  const worksheetsMap = new Map<string, { label: string; hrefSlug: string; worksheetFormat: string }>();

  for (const course of courses) {
    groups.set(course.group.id, { label: course.group.label, key: course.group.key });
    subjects.set(course.subject.id, { label: course.subject.label, key: course.subject.key });
    if (course.courseVariant) {
      variants.set(course.courseVariant.id, {
        label: course.courseVariant.label,
        short: course.courseVariant.short,
      });
    }

    for (const topic of course.topics) {
      if (!topicsMap.has(topic.topicId)) {
        topicsMap.set(topic.topicId, {
          label: topic.label,
          hrefSlug: topic.topicId,
        });
      }

      for (const chapter of topic.chapters) {
        if (!chaptersMap.has(chapter.chapterId)) {
          chaptersMap.set(chapter.chapterId, {
            label: chapter.label,
            hrefSlug: chapter.chapterId,
          });
        }

        for (const worksheet of chapter.worksheets) {
          if (!worksheetsMap.has(worksheet.worksheetId)) {
            worksheetsMap.set(worksheet.worksheetId, {
              label: worksheet.label,
              hrefSlug: worksheet.worksheetId,
              worksheetFormat: worksheet.worksheetFormat,
            });
          }
        }
      }
    }
  }

  // -------------------------------------------------------------------------
  // 2) groups
  // -------------------------------------------------------------------------
  lines.push("-- Groups");
  for (const [groupId, { label, key }] of groups) {
    lines.push(
      `INSERT INTO groups (group_id, group_label, group_key) VALUES (${esc(groupId)}, ${esc(label)}, ${esc(key)}) ON CONFLICT (group_id) DO UPDATE SET group_label = EXCLUDED.group_label, group_key = EXCLUDED.group_key;`,
    );
  }
  lines.push("");

  // -------------------------------------------------------------------------
  // 3) subjects
  // -------------------------------------------------------------------------
  lines.push("-- Subjects");
  for (const [subjectId, { label, key }] of subjects) {
    lines.push(
      `INSERT INTO subjects (subject_id, subject_label, subject_key) VALUES (${esc(subjectId)}, ${esc(label)}, ${esc(key)}) ON CONFLICT (subject_id) DO UPDATE SET subject_label = EXCLUDED.subject_label, subject_key = EXCLUDED.subject_key;`,
    );
  }
  lines.push("");

  // -------------------------------------------------------------------------
  // 4) course_variants
  // -------------------------------------------------------------------------
  if (variants.size > 0) {
    lines.push("-- Course variants");
    for (const [variantId, { label, short }] of variants) {
      lines.push(
        `INSERT INTO course_variants (variant_id, variant_label, variant_short) VALUES (${esc(variantId)}, ${esc(label)}, ${esc(short)}) ON CONFLICT (variant_id) DO UPDATE SET variant_label = EXCLUDED.variant_label, variant_short = EXCLUDED.variant_short;`,
      );
    }
    lines.push("");
  }

  // -------------------------------------------------------------------------
  // 5) topics
  // -------------------------------------------------------------------------
  lines.push("-- Topics");
  for (const [topicId, { label, hrefSlug }] of topicsMap) {
    lines.push(
      `INSERT INTO topics (topic_id, label, href_slug) VALUES (${esc(topicId)}, ${esc(label)}, ${esc(hrefSlug)}) ON CONFLICT (topic_id) DO UPDATE SET label = EXCLUDED.label, href_slug = EXCLUDED.href_slug;`,
    );
  }
  lines.push("");

  // -------------------------------------------------------------------------
  // 6) chapters
  // -------------------------------------------------------------------------
  lines.push("-- Chapters");
  for (const [chapterId, { label, hrefSlug }] of chaptersMap) {
    lines.push(
      `INSERT INTO chapters (chapter_id, label, href_slug) VALUES (${esc(chapterId)}, ${esc(label)}, ${esc(hrefSlug)}) ON CONFLICT (chapter_id) DO UPDATE SET label = EXCLUDED.label, href_slug = EXCLUDED.href_slug;`,
    );
  }
  lines.push("");

  // -------------------------------------------------------------------------
  // 7) worksheets
  // -------------------------------------------------------------------------
  lines.push("-- Worksheets");
  for (const [worksheetId, { label, hrefSlug, worksheetFormat }] of worksheetsMap) {
    lines.push(
      `INSERT INTO worksheets (worksheet_id, label, href_slug, worksheet_format) VALUES (${esc(worksheetId)}, ${esc(label)}, ${esc(hrefSlug)}, ${esc(worksheetFormat)}) ON CONFLICT (worksheet_id) DO UPDATE SET label = EXCLUDED.label, href_slug = EXCLUDED.href_slug, worksheet_format = EXCLUDED.worksheet_format;`,
    );
  }
  lines.push("");

  // -------------------------------------------------------------------------
  // 8) courses + junction tables
  // -------------------------------------------------------------------------
  for (const course of courses) {
    const variantId = course.courseVariant?.id ?? null;

    lines.push(`-- Course: ${course.id}`);
    lines.push(
      `INSERT INTO courses (course_id, group_id, subject_id, variant_id, slug, icon, color, worksheet_format, is_listed, is_public) VALUES (${esc(course.id)}, ${esc(course.group.id)}, ${esc(course.subject.id)}, ${esc(variantId)}, ${esc(course.slug)}, ${esc(course.icon)}, ${esc(course.color)}, 'web', ${bool(course.isListed)}, ${bool(course.isPublic)}) ON CONFLICT (course_id) DO UPDATE SET group_id = EXCLUDED.group_id, subject_id = EXCLUDED.subject_id, variant_id = EXCLUDED.variant_id, slug = EXCLUDED.slug, icon = EXCLUDED.icon, color = EXCLUDED.color, is_listed = EXCLUDED.is_listed, is_public = EXCLUDED.is_public, updated_at = NOW();`,
    );

    // Delete and reinsert junction tables to handle structural changes
    lines.push(`DELETE FROM course_topics WHERE course_id = ${esc(course.id)};`);

    for (const [topicIndex, topic] of course.topics.entries()) {
      const topicStatus =
        topicIndex === 0 ? "current" : topicIndex === 1 ? "planned" : "locked";

      lines.push(
        `INSERT INTO course_topics (course_id, topic_id, display_order, status) VALUES (${esc(course.id)}, ${esc(topic.topicId)}, ${topicIndex}, ${esc(topicStatus)});`,
      );

      for (const [chapterIndex, chapter] of topic.chapters.entries()) {
        const chapterStatus =
          topicIndex === 0 && chapterIndex === 0 ? "current" : "locked";

        lines.push(
          `INSERT INTO course_chapters (course_id, topic_id, chapter_id, display_order, status) VALUES (${esc(course.id)}, ${esc(topic.topicId)}, ${esc(chapter.chapterId)}, ${chapterIndex}, ${esc(chapterStatus)});`,
        );

        for (const [worksheetIndex, worksheet] of chapter.worksheets.entries()) {
          lines.push(
            `INSERT INTO course_worksheets (course_id, topic_id, chapter_id, worksheet_id, display_order, is_hidden) VALUES (${esc(course.id)}, ${esc(topic.topicId)}, ${esc(chapter.chapterId)}, ${esc(worksheet.worksheetId)}, ${worksheetIndex}, FALSE);`,
          );
        }
      }
    }
    lines.push("");
  }

  await writeSQLFile(path, lines.join("\n"));
}
