import type { CoursePlan } from "@schema/course-plan"
import path from "node:path";

export function buildSidebar(course: CoursePlan) {
    return {
        relativePath: path.join("sidebars", course.group, `${course.course_variant}.ts`),
        content: buildSidebarContent(course)
    };
}

function buildSidebarContent(course: CoursePlan) {

    const topics = Object.entries(
        course.topics.reduce((acc, item) => {
            acc[item.topic] = acc[item.topic] !== undefined;
            return acc;
        }, {} as Record<string, boolean>)
    )
        .filter(([_, moreThanOne]) => moreThanOne)
        .map(([topic]) => topic);

    const sidebarEntries = topics
        .map(topic => `${topic}: [{type: 'autogenerated', dirName: '${topic}'}]`)
        .join(",\n");

    return `import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {${sidebarEntries}
};

export default sidebars;
`;
}
