import type { CoursePlan } from "@schema/coursePlan"
import path from "node:path";

export function buildSidebar(course: CoursePlan) {
    return {
        relativePath: path.join("sidebars", course.group, `${course.slug}.ts`),
        content: buildSidebarContent(course)
    };
}

function buildSidebarContent(course: CoursePlan) {

    const sidebarEntries = course.topics
        .map(({topic}) => `${topic}: [{type: 'autogenerated', dirName: '${topic}'}]`)
        .join(",\n");

    return `import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {${sidebarEntries}
};

export default sidebars;
`;
}
