import type { CoursePlan } from "@schema/coursePlan";

export function renderSidebar(course: CoursePlan): string {
  const sidebarEntries = course.topics
    .map(({ topic }) => `  ${topic}: [{ type: 'autogenerated', dirName: '${topic}' }]`)
    .join(",\n");

  return `import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
${sidebarEntries}
};

export default sidebars;
`;
}
