import { TopicProgress } from "@builder/computeCourseProgress";

export function renderSidebar(topics: TopicProgress[]): string {
  const sidebarEntries = topics
    .map(({ topic }) => `  ${topic}: [{ type: 'autogenerated', dirName: '${topic}' }]`)
    .join(",\n");

  return `import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
${sidebarEntries}
};

export default sidebars;
`;
}
